# mysql 配置
mysql:
  # 数据库 host
  host: 'localhost'
  # 数据库端口
  port: 3306
  # 数据库用户名
  username: 'root'
  # 数据库密码
  password: 'j!Y6hTwR'
  # 连接数据库信息
  database: 'g-rebirth'
  # 是否自动同步数据库表格式
  synchronize: false
# 服务启动端口
port: 3000